package compiler;

public enum LexemeToken {
    NUMBER, STRING, IDENTIFIER, LEFT_PAREN, RIGHT_PAREN, COMMA,
    BINARY_MUL, BINARY_DIV, BINARY_SUB, BINARY_ADD, SEMICOLON, ASSIGNMENT_OP, UNKNOWN, EOF,
    COMP_EQUAL, COMP_GREATER, COMP_LESS, COMP_LESS_EQUAL, COMP_GREATER_EQUAL,
    KEYWORD_IF, KEYWORD_AND, KEYWORD_OR, KEYWORD_FUNC, KEYWORD_LET, KEYWORD_RETURN
}
